# cat user.yml
---
- hosts: preview
  remote_user: root
  tasks:

    - name: git pull
      git: repo=git@github.com:bluestacks/bst-server-zh.git
           dest=/var/www/html/preview_bst-server-zh/bst-server-zh
           version=bsdev

    # python /var/www/html/preview_bst-server-zh/bst-server-zh/manage.py collectstatic --noinput 
    - name: collectstatic
      shell: python /var/www/html/preview_bst-server-zh/bst-server-zh/manage.py collectstatic --noinput 

    - name: restart httpd
      service: name=httpd state=restarted
